<?php

namespace DrinkBundle\Repository;

/**
 * DetallePedidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetallePedidoRepository extends \Doctrine\ORM\EntityRepository
{
}
