<?php

namespace DrinkBundle\Repository;

/**
 * estadoPedidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class estadoPedidoRepository extends \Doctrine\ORM\EntityRepository
{
}
