user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    type: rest
    prefix: /api

drink_dispositivo:
    resource: "@DrinkBundle/Controller/DispositivoController.php"
    type:     annotation

drink_estado_pedido:
    resource: "@DrinkBundle/Controller/EstadoPedidoController.php"
    type:     annotation

drink_pedido:
    resource: "@DrinkBundle/Controller/PedidoController.php"
    type:     annotation

drink:
    resource: "@DrinkBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
