detallePedido_index:
    path:     /
    defaults: { _controller: "DrinkBundle:DetallePedido:index" }
    methods:  GET

detallePedido_show:
    path:     /{id}/show
    defaults: { _controller: "DrinkBundle:DetallePedido:show" }
    methods:  GET

detallePedido_new:
    path:     /new
    defaults: { _controller: "DrinkBundle:DetallePedido:new" }
    methods:  [GET, POST]

detallePedido_edit:
    path:     /{id}/edit
    defaults: { _controller: "DrinkBundle:DetallePedido:edit" }
    methods:  [GET, POST]

detallePedido_delete:
    path:     /{id}/delete
    defaults: { _controller: "DrinkBundle:DetallePedido:delete" }
    methods:  DELETE
