estado_pedido_index:
    path:     /
    defaults: { _controller: "DrinkBundle:EstadoPedido:index" }
    methods:  GET

estado_pedido_show:
    path:     /{id}/show
    defaults: { _controller: "DrinkBundle:EstadoPedido:show" }
    methods:  GET

estado_pedido_new:
    path:     /new
    defaults: { _controller: "DrinkBundle:EstadoPedido:new" }
    methods:  [GET, POST]

estado_pedido_edit:
    path:     /{id}/edit
    defaults: { _controller: "DrinkBundle:EstadoPedido:edit" }
    methods:  [GET, POST]

estado_pedido_delete:
    path:     /{id}/delete
    defaults: { _controller: "DrinkBundle:EstadoPedido:delete" }
    methods:  DELETE
