producto_index:
    path:     /
    defaults: { _controller: "DrinkBundle:Producto:index" }
    methods:  GET

producto_show:
    path:     /{id}/show
    defaults: { _controller: "DrinkBundle:Producto:show" }
    methods:  GET

producto_new:
    path:     /new
    defaults: { _controller: "DrinkBundle:Producto:new" }
    methods:  [GET, POST]

producto_edit:
    path:     /{id}/edit
    defaults: { _controller: "DrinkBundle:Producto:edit" }
    methods:  [GET, POST]

producto_delete:
    path:     /{id}/delete
    defaults: { _controller: "DrinkBundle:Producto:delete" }
    methods:  DELETE

producto_edit_ajax:
    path:     /ajax/editar
    defaults: { _controller: "DrinkBundle:Producto:editAjax" }

